"""
Construction terminology standardization for commercial projects.

Maps common abbreviations, acronyms, and variations to standard terms
so the conflict detector and cross-reference engine can match entities
even when different disciplines use different names for the same thing.
"""

# ── Abbreviation → Full Term ──────────────────────────────
ABBREVIATIONS = {
    # Structural
    "BOS": "BOTTOM OF STEEL",
    "B.O.S.": "BOTTOM OF STEEL",
    "TOS": "TOP OF STEEL",
    "T.O.S.": "TOP OF STEEL",
    "TOW": "TOP OF WALL",
    "T.O.W.": "TOP OF WALL",
    "BOW": "BOTTOM OF WALL",
    "TOC": "TOP OF CONCRETE",
    "T.O.C.": "TOP OF CONCRETE",
    "TOF": "TOP OF FOOTING",
    "FFE": "FINISH FLOOR ELEVATION",
    "F.F.E.": "FINISH FLOOR ELEVATION",
    "SOG": "SLAB ON GRADE",
    "CLR": "CLEAR",
    "EL": "ELEVATION",
    "ELEV": "ELEVATION",
    "TYP": "TYPICAL",
    "SIM": "SIMILAR",
    "NIC": "NOT IN CONTRACT",
    "OFCI": "OWNER FURNISHED CONTRACTOR INSTALLED",
    "OFOI": "OWNER FURNISHED OWNER INSTALLED",
    "UNO": "UNLESS NOTED OTHERWISE",
    "U.N.O.": "UNLESS NOTED OTHERWISE",
    "NTS": "NOT TO SCALE",
    "EQ": "EQUAL",
    "EA": "EACH",
    "OC": "ON CENTER",
    "O.C.": "ON CENTER",
    "EW": "EACH WAY",
    "E.W.": "EACH WAY",
    "EF": "EACH FACE",
    "E.F.": "EACH FACE",
    "AFF": "ABOVE FINISH FLOOR",
    "A.F.F.": "ABOVE FINISH FLOOR",
    "ABV": "ABOVE",
    "BLW": "BELOW",
    "ADJ": "ADJACENT",
    "CONT": "CONTINUOUS",
    "MAX": "MAXIMUM",
    "MIN": "MINIMUM",
    "APPROX": "APPROXIMATELY",
    "DIA": "DIAMETER",
    "RAD": "RADIUS",
    "THK": "THICK",
    "LG": "LONG",
    "WD": "WIDE",
    "HT": "HEIGHT",
    "DP": "DEEP",
    "GA": "GAUGE",
    "GALV": "GALVANIZED",
    "SS": "STAINLESS STEEL",
    "AL": "ALUMINUM",
    "HM": "HOLLOW METAL",
    "WD": "WOOD",
    "GYP BD": "GYPSUM BOARD",
    "GWB": "GYPSUM WALL BOARD",
    "ACT": "ACOUSTIC CEILING TILE",
    "VCT": "VINYL COMPOSITION TILE",
    "LVT": "LUXURY VINYL TILE",
    "FRP": "FIBER REINFORCED PANEL",
    "CMU": "CONCRETE MASONRY UNIT",
    "NW": "NORMAL WEIGHT",
    "LW": "LIGHTWEIGHT",
    "PSI": "POUNDS PER SQUARE INCH",
    "KSI": "KIPS PER SQUARE INCH",
    "PLF": "POUNDS PER LINEAR FOOT",
    "PSF": "POUNDS PER SQUARE FOOT",
    "KLF": "KIPS PER LINEAR FOOT",

    # Mechanical / HVAC
    "AHU": "AIR HANDLING UNIT",
    "RTU": "ROOFTOP UNIT",
    "FCU": "FAN COIL UNIT",
    "MAU": "MAKEUP AIR UNIT",
    "ERU": "ENERGY RECOVERY UNIT",
    "ERV": "ENERGY RECOVERY VENTILATOR",
    "HRU": "HEAT RECOVERY UNIT",
    "VRF": "VARIABLE REFRIGERANT FLOW",
    "WSHP": "WATER SOURCE HEAT PUMP",
    "VAV": "VARIABLE AIR VOLUME",
    "FPB": "FAN POWERED BOX",
    "CAV": "CONSTANT AIR VOLUME",
    "CUH": "CABINET UNIT HEATER",
    "UH": "UNIT HEATER",
    "EF": "EXHAUST FAN",
    "SF": "SUPPLY FAN",
    "RF": "RETURN FAN",
    "CFM": "CUBIC FEET PER MINUTE",
    "BTU": "BRITISH THERMAL UNIT",
    "MBH": "THOUSAND BTU PER HOUR",
    "GPM": "GALLONS PER MINUTE",
    "CHW": "CHILLED WATER",
    "CW": "COLD WATER",
    "HW": "HOT WATER",
    "HHW": "HEATING HOT WATER",
    "CWR": "CHILLED WATER RETURN",
    "CWS": "CHILLED WATER SUPPLY",
    "BAS": "BUILDING AUTOMATION SYSTEM",
    "BMS": "BUILDING MANAGEMENT SYSTEM",
    "DDC": "DIRECT DIGITAL CONTROL",

    # Electrical
    "MDP": "MAIN DISTRIBUTION PANEL",
    "SDP": "SUB DISTRIBUTION PANEL",
    "MSB": "MAIN SWITCHBOARD",
    "LP": "LIGHTING PANEL",
    "DP": "DISTRIBUTION PANEL",
    "PP": "POWER PANEL",
    "MCC": "MOTOR CONTROL CENTER",
    "ATS": "AUTOMATIC TRANSFER SWITCH",
    "GEN": "GENERATOR",
    "UPS": "UNINTERRUPTIBLE POWER SUPPLY",
    "XFMR": "TRANSFORMER",
    "VFD": "VARIABLE FREQUENCY DRIVE",
    "MCA": "MINIMUM CIRCUIT AMPACITY",
    "MOCP": "MAXIMUM OVERCURRENT PROTECTION",
    "KAIC": "KILO AMPERE INTERRUPTING CAPACITY",
    "AIC": "AMPERE INTERRUPTING CAPACITY",
    "EMT": "ELECTRICAL METALLIC TUBING",
    "IMC": "INTERMEDIATE METAL CONDUIT",
    "RGS": "RIGID GALVANIZED STEEL",
    "RMC": "RIGID METAL CONDUIT",
    "PVC": "POLYVINYL CHLORIDE",
    "LFMC": "LIQUIDTIGHT FLEXIBLE METAL CONDUIT",
    "GFCI": "GROUND FAULT CIRCUIT INTERRUPTER",
    "AFCI": "ARC FAULT CIRCUIT INTERRUPTER",

    # Fire Protection
    "FDC": "FIRE DEPARTMENT CONNECTION",
    "PIV": "POST INDICATOR VALVE",
    "FACP": "FIRE ALARM CONTROL PANEL",
    "QR": "QUICK RESPONSE",
    "SR": "STANDARD RESPONSE",

    # Plumbing
    "DWV": "DRAIN WASTE VENT",
    "SD": "STORM DRAIN",
    "RD": "ROOF DRAIN",
    "WC": "WATER CLOSET",
    "LAV": "LAVATORY",
    "UR": "URINAL",
    "EWC": "ELECTRIC WATER COOLER",
    "BFP": "BACKFLOW PREVENTER",
    "PRV": "PRESSURE REDUCING VALVE",
    "RPZA": "REDUCED PRESSURE ZONE ASSEMBLY",

    # Technology
    "MDF": "MAIN DISTRIBUTION FRAME",
    "IDF": "INTERMEDIATE DISTRIBUTION FRAME",
    "WAP": "WIRELESS ACCESS POINT",
    "AP": "ACCESS POINT",
    "NVR": "NETWORK VIDEO RECORDER",
    "POE": "POWER OVER ETHERNET",
    "CCTV": "CLOSED CIRCUIT TELEVISION",
}


def expand(abbrev: str) -> str:
    """Expand an abbreviation to its full term. Returns original if not found."""
    return ABBREVIATIONS.get(abbrev.upper().strip(), abbrev)


def normalize_term(text: str) -> str:
    """Normalize a construction term by expanding common abbreviations."""
    words = text.upper().split()
    return " ".join(ABBREVIATIONS.get(w, w) for w in words)
